# Frontier Exploration Parameters

accurate_frontiers: true                  # True: explicitly compute all frontier voxels
                                          # (may degrade performance),
                                          # False: estimate frontier voxels by checking only some neighbors (detection
                                          # depends on previous views)
checking_distance: 1.0                    # Distance in *voxelsizes* where we check for known voxels
surface_distance_threshold_factor: 3.5    # Distance in *voxelsizes* upto which voxels near the surface are marked as occupied
slice_level: 1.0                          # Height at which the ESDF slice is provided, in *meters*
min_frontier_size: 3                      # Minimum points required in a frontier
upper_range: -0.2                         # Max height of points with respect to slice level, in *meters*
lower_range: 0.8                          # Min height of points with respect to slice level, in *meters*
