# Frontier Exploration Parameters

accurate_frontiers: true                  # True: explicitly compute all frontier voxels
                                          # (may degrade performance),
                                          # False: estimate frontier voxels by checking only some neighbors (detection
                                          # depends on previous views)
checking_distance: 1.0                    # Distance in *voxelsizes* where we check for known voxels
occupancy_distance: 3.5                   # Distance in *voxelsizes* upto which voxels near the surface are marked as occupied
slice_level: 1.0                          # Height at which the ESDF slice is provided, in *meters*
min_frontier_size: 3                      # Minimum points required in a frontier
upper_range: -0.2                         # Only consider those points for frontiers
lower_range: 0.8                          # whose height lies in ($slice_level - $lower_range, $slice_level + $upper_range)
voxel_size: 0.2                           # size of voxels used in maps, in *meters*
visualize: true                           # whether to publish RViz visualizations
clear_radius: 1.0                         # Radius of sphere around the MAV to consider as free, in *meters*
update_frontiers_every_n_sec: 0.25        # Set frontier update rate, in *seconds*
