# General Purpose Parameters

# debug flags
verbose: false                      # Print additional debug and timing information.
visualize: true                     # Whether to publish information for visualization in RViz.

# frames
world_frame: world                  # The base frame used when looking up tf transforms. 
                                    # This is also the frame that most outputs are given in.
frame_id: world                     # Global fixed frame id.
local_frame_id: world               # Frame name for the quadrotor base.

# robot constraints
robot_radius: 0.45                  # Robot sphere radius, to be used for planning,  in metres.
traversability_radius: 0.45         # Radius in metres, of the space around the robot to be considered as occupied.
                                    # Recommended value: equal to robot_radius     
voxel_size: 0.2